---
- hosts: local

  tasks:
    - name: clone the Configuration repository
      git: accept_hostkey=yes dest={{ brunombsilva.config.clone_dir }} repo={{ brunombsilva.config.repository }} version={{brunombsilva.config.branch}} recursive=false

    - name: install vim
      shell: add-apt-repository ppa:jonathonf/vim && apt-get -y update  && apt-get -y install vim
      become: true
      args:
         creates: /usr/bin/vim

    - name: configuration submodules
      shell: git submodule update --init
      args:
        chdir: "{{ brunombsilva.config.clone_dir }}" 
      register: task_result
      until: task_result.rc == 0
      retries: 3
      ignore_errors: yes
      when: false

    - name: ensure directories
      file: dest={{ brunombsilva.home_dir }}/{{item}} state=directory
      with_items:
        - .ssh
        - .config

    - name: configuration files symlinks
      file: src={{ brunombsilva.config.clone_dir }}/_{{ item }} dest={{ brunombsilva.home_dir }}/.{{ item }} state=link force=yes
      with_items:
        - bash.bashrc
        - bashrc
        - bash_prompt
        - inputrc
        - bash_profile
        - bash_logout
        - gitconfig
        - gitignore
        - tmux.conf
        - tmuxinator
        - tigrc
        - curlrc
        - my.cnf
        - grcat

    - name: vim configuration files symlinks
      file: src={{ brunombsilva.config.clone_dir }}/vim/_{{ item }} dest={{ brunombsilva.home_dir }}/.{{ item }} state=link force=yes
      with_items:
        - vimrc
        - vim
        - gvimrc

    - name: ssh configuration symlinks
      file: src={{ brunombsilva.config.clone_dir }}/_sshconfig dest={{ brunombsilva.home_dir }}/.ssh/config state=link force=yes

    - name: powerline configuration symlinks
      file: src={{ brunombsilva.config.clone_dir }}/powerline dest={{ brunombsilva.home_dir }}/.config/powerline state=link force=yes

    - name: install packages
      become: true
      apt: pkg={{ item }}
      with_items: 
        - tmux
        - libncursesw5-dev
        - htop
        - exuberant-ctags
        - ngrep
        - ruby-full
        - nodejs
        - npm
        - grc
        - lnav
        - git-extras
        - wget

    - name: rbenv
      git: accept_hostkey=yes dest=~/.rbenv repo=https://github.com/rbenv/rbenv.git
    
    - name: rbenv ruby-build
      git: accept_hostkey=yes dest=~/.rbenv/plugins/ruby-build repo=https://github.com/rbenv/ruby-build.git 

    - name: rbenv - bash
      shell: cd ~/.rbenv && src/configure && make -C src

    - name: clone tig
      git: accept_hostkey=yes dest=/tmp/tig repo=http://github.com/jonas/tig version=master

    #- name: install composer
      #become: true
      #shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    #- name: install tig
      #become: true
      #shell: make /usr/local && make install prefix=/usr/local
      #args:
          #chdir: /tmp/tig
     
    - gem: name=lolcat state=latest
    - gem: name=sass state=latest
    #- gem: name=ruby-beautify state=latest

    #- gem: name=mdl state=latest

    - name: clone z
      git: accept_hostkey=yes dest=~/z repo=https://github.com/rupa/z version=master

    - name: download python
      unarchive: src=https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz dest=/tmp/ remote_src=yes
      when: false

    - name: install python dependencies
      apt: pkg={{ item }}
      become: true
      when: false
      with_items:
         - build-essential
         - libreadline-gplv2-dev 
         - libncursesw5-dev 
         - libssl-dev 
         - libsqlite3-dev 
         - tk-dev 
         - libgdbm-dev 
         - libc6-dev 
         - libbz2-dev

    - name: install phyton
      shell: ./configure && make && make install
      args:
        chdir: /tmp/Python-2.7.9
      become: true
      when: false

    - name: download pip
      get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp/ remote_src=yes
    - name: install pip
      shell: python /tmp/get-pip.py
      become: true

    - name: http-prompt
      pip: name=http-prompt
      become: true

    - name: powerline
      pip: name=powerline-status
      become: true

    - name: powerline git status
      pip: name=powerline-gitstatus
      become: true

    - name: npm dependencies
      npm: name={{ item }} global=yes state=latest
      become: true
      with_items:
        - js-yaml
        - js-beautify

    #- name: install twig lint
      #shell: composer global require "asm89/twig-lint" "@stable"
