---
- hosts: vagrant

  tasks:
    - name: clone the Configuration repository
      git: accept_hostkey=yes dest={{ brunombsilva.config.clone_dir }} repo={{ brunombsilva.config.repository }} version={{brunombsilva.config.branch}}

    - name: configuration files symlinks
      file: src={{ brunombsilva.config.clone_dir }}/_{{ item }} dest={{ brunombsilva.home_dir }}/.{{ item }} state=link force=yes
      with_items:
        - bash.bashrc
        - bashrc
        - bash_prompt
        - inputrc
        - bash_profile
        - bash_logout
        - gitconfig
        - gitignore
        - tmux.conf
        - tmuxinator
        - tigrc
        - curlrc
        - my.cnf
        - grcat

    - name: vim configuration files symlinks
      file: src={{ brunombsilva.config.clone_dir }}/vim/_{{ item }} dest={{ brunombsilva.home_dir }}/.{{ item }} state=link force=yes
      with_items:
        - vimrc
        - vim
        - gvimrc

    - name: ssh configuration symlinks
      file: src={{ brunombsilva.config.clone_dir }}/_sshconfig dest={{ brunombsilva.home_dir }}/.ssh/config state=link force=yes

    - name: powerline configuration symlinks
      file: src={{ brunombsilva.config.clone_dir }}/powerline dest={{ brunombsilva.home_dir }}/.config/powerline state=link force=yes

    - name: install packages
      sudo: yes
      apt: pkg={{ item }}
      with_items: 
        - tmux
        - libncursesw5-dev
        - htop
        - exuberant-ctags
        - ngrep
        - ruby-full
        - nodejs
        - npm
        - grc
        - lnav
        - git-extras

    - name: rbenv
      git: accept_hostkey=yes dest=~/.rbenv repo=https://github.com/rbenv/rbenv.git
    
    - name: rbenv ruby-build
      git: accept_hostkey=yes dest=~/.rbenv/plugins/ruby-build repo=https://github.com/rbenv/ruby-build.git 

    - name: rbenv - bash
      shell: cd ~/.rbenv && src/configure && make -C src

    - name: clone tig
      git: accept_hostkey=yes dest=/tmp/tig repo=http://github.com/jonas/tig version=master

    #- name: install composer
      #sudo: yes
      #shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

    #- name: install tig
      #sudo: yes
      #shell: make /usr/local && make install prefix=/usr/local
      #args:
          #chdir: /tmp/tig
     
    - gem: name=lolcat state=latest
    - gem: name=sass state=latest
    - gem: name=ruby-beautify state=latest

    #- gem: name=mdl state=latest

    - name: clone z
      git: accept_hostkey=yes dest=~/z repo=https://github.com/rupa/z version=master

    - name: http-prompt
      pip: name=http-prompt

    - name: powerline
      pip: name=powerline-status

    - name: powerline git status
      pip: name=powerline-gitstatus

    - name: npm dependencies
      npm: name={{ item }} global=yes state=latest
      sudo: yes
      with_items:
        - js-yaml
        - js-beautify

    #- name: install twig lint
      #shell: composer global require "asm89/twig-lint" "@stable"
