---
- hosts: vagrant

  tasks:
    - name: clone the Configuration repository
      git: accept_hostkey=yes dest={{ brunombsilva.config.clone_dir }} repo={{ brunombsilva.config.repository }} version={{brunombsilva.config.branch}}

    - name: configuration files symlinks
      file: src={{ brunombsilva.config.clone_dir }}/_{{ item }} dest={{ brunombsilva.home_dir }}/.{{ item }} state=link force=yes
      with_items:
        - bashrc
        - bash_aliases
        - bash_prompt
        - inputrc
        - bash_profile
        - bash_logout
        - gitconfig
        - gitignore
        - tmux.conf
        - tmuxinator
        - tigrc

    - name: vim configuration files symlinks
      file: src={{ brunombsilva.config.clone_dir }}/vim/_{{ item }} dest={{ brunombsilva.home_dir }}/.{{ item }} state=link force=yes
      with_items:
        - vimrc
        - vim
        - gvimrc

    - name: ssh configuration symlinks
      file: src={{ brunombsilva.config.clone_dir }}/_sshconfig dest={{ brunombsilva.home_dir }}/.ssh/config state=link force=yes

    - name: install packages
      sudo: yes
      apt: pkg={{ item }}
      with_items: 
        - tmux
        - libncursesw5-dev
        - htop
        - exuberant-ctags
        - ngrep

    - name: clone tig
      git: accept_hostkey=yes dest=/tmp/tig repo=http://github.com/jonas/tig version=master

    - name: install tig
      sudo: yes
      shell: make /usr/local && make install prefix=/usr/local
      args:
          chdir: /tmp/tig
     
    - gem: name=lolcat state=latest

    - name: clone z
      git: accept_hostkey=yes dest=~/z repo=https://github.com/rupa/z version=master

